In [123]:
from tensorflow.keras.preprocessing.text import one_hot

In [124]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [125]:
## Define the vocabulary size
voc_size=10000

In [126]:
## one Hot represntation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[6984, 2628, 7764, 9156],
 [6984, 2628, 7764, 5216],
 [6984, 5751, 7764, 1925],
 [9306, 4139, 1336, 7968, 7506],
 [9306, 4139, 1336, 7968, 352],
 [4851, 6984, 6281, 7764, 6153],
 [2883, 9663, 366, 7968]]

In [127]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [128]:
import numpy as np
embedded_docs = np.array(embedded_docs)  # Ensure shape = (n_samples, sent_length)

In [129]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6984 2628 7764 9156]
 [   0    0    0    0 6984 2628 7764 5216]
 [   0    0    0    0 6984 5751 7764 1925]
 [   0    0    0 9306 4139 1336 7968 7506]
 [   0    0    0 9306 4139 1336 7968  352]
 [   0    0    0 4851 6984 6281 7764 6153]
 [   0    0    0    0 2883 9663  366 7968]]


In [130]:
## feature representation
dim=10

In [131]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))

In [132]:
model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_14 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [133]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step


array([[[ 0.03811521, -0.02413552, -0.04535296,  0.01541999,
         -0.04338134, -0.00174761,  0.04935363, -0.04678794,
          0.0370522 , -0.00381992],
        [ 0.03811521, -0.02413552, -0.04535296,  0.01541999,
         -0.04338134, -0.00174761,  0.04935363, -0.04678794,
          0.0370522 , -0.00381992],
        [ 0.03811521, -0.02413552, -0.04535296,  0.01541999,
         -0.04338134, -0.00174761,  0.04935363, -0.04678794,
          0.0370522 , -0.00381992],
        [ 0.03811521, -0.02413552, -0.04535296,  0.01541999,
         -0.04338134, -0.00174761,  0.04935363, -0.04678794,
          0.0370522 , -0.00381992],
        [-0.01866259, -0.03196175, -0.03434245, -0.00323693,
         -0.04687105, -0.01525497,  0.04653193,  0.00820097,
         -0.00269007,  0.04763177],
        [-0.03006891, -0.01920972,  0.04740466,  0.02778408,
          0.02830415, -0.00727595, -0.04115163,  0.04308167,
          0.04842355, -0.04334983],
        [ 0.03254938, -0.01731664, -0.02658359, -0.0

In [134]:
embedded_docs[5]

array([   0,    0,    0, 4851, 6984, 6281, 7764, 6153])

In [136]:
model.predict(embedded_docs[5])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None